Splitwise:
  match: 'Scott'
  hdr:
    date: 'Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Scott'
  negative_debit: True
  rules: 'expenses_splitwise.csv'
CapitalOne:
  match: 'Card No.'
  hdr:
    date: 'Transaction Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Debit'
  negative_debit: False
  rules: 'expenses_credit.csv'
Splitwise Empty: 
  match: 'You have no '
  pass: True
Citi:
  match: 'Status'
  hdr:
    date: 'Date'
    desc: 'Description'
    category: ''
    debit: 'Debit'
  negative_debit: False
  rules: 'expenses_credit.csv'
Chase:
  match: 'Memo'
  hdr:
    date: 'Transaction Date'
    desc: 'Description'
    category: 'Category'
    debit: 'Amount'
  negative_debit: True
  rules: 'expenses_credit.csv'
Spliit:
  json_header_match: "participants"
  participant_id: "Xa5IFvRWcDOY9FPAaSrmI"
  hdr:
    date: 'expenseDate'
    desc: 'title'
    category: 'category.name'
    debit: 'computedAmount'
  rules: 'expenses_spliit.csv'
